/D400/D400:
  ros__parameters:
    camera_name: "D400"
    serial_no: ""
    usb_port_id: ""
    device_type: "d4."
    config_file: ""
    unite_imu_method: 2
    json_file_path: ""
    log_level: "info"
    output: "screen"
    depth_module.profile: "0,0,0"
    enable_depth: true
    rgb_camera.profile: "0,0,0"
    enable_color: true
    enable_infra1: true
    enable_infra2: true
    infra_rgb: false
    tracking_module.profile: "0,0,0"
    enable_fisheye1: true
    enable_fisheye2: true
    enable_confidence: true
    gyro_fps: 0
    accel_fps: 0
    enable_gyro: false
    enable_accel: false
    enable_pose: true
    pose_fps: 200
    pose_qos: "SYSTEM_DEFAULT"
    pointcloud.enable: false
    pointcloud.stream_filter: 2
    pointcloud.stream_index_filter: -1
    enable_sync: false
    align_depth.enable: false
    colorizer.enable: false
    clip_distance: -2.
    linear_accel_cov: 0.01
    initial_reset: false
    allow_no_texture_points: false
    ordered_pc: false
    calib_odom_file: ""
    topic_odom_in: ""
    tf_publish_rate: 0.0
    diagnostics_period: 0.0
    decimation_filter.enable: false
    rosbag_filename: ""
    depth_module.exposure.1: 7500
    depth_module.gain.1: 16
    depth_module.exposure.2: 1
    depth_module.gain.2: 16
    wait_for_device_timeout: -1.
    reconnect_timeout: 6.
/T265/T265:
  ros__parameters:
    camera_name: "T265"
    serial_no: ""
    usb_port_id: ""
    device_type: "t265"
    config_file: ""
    unite_imu_method: 2
    json_file_path: ""
    log_level: "info"
    output: "screen"
    depth_module.profile: "0,0,0"
    enable_depth: true
    rgb_camera.profile: "0,0,0"
    enable_color: true
    enable_infra1: true
    enable_infra2: true
    infra_rgb: false
    tracking_module.profile: "0,0,0"
    enable_fisheye1: true
    enable_fisheye2: true
    enable_confidence: true
    gyro_fps: 0
    accel_fps: 0
    enable_gyro: false
    enable_accel: false
    enable_pose: true
    pose_fps: 200
    pose_qos: "SYSTEM_DEFAULT"
    pointcloud.enable: false
    pointcloud.stream_filter: 2
    pointcloud.stream_index_filter: -1
    enable_sync: false
    align_depth.enable: false
    colorizer.enable: false
    clip_distance: -2.
    linear_accel_cov: 0.01
    initial_reset: false
    allow_no_texture_points: false
    ordered_pc: false
    calib_odom_file: ""
    topic_odom_in: ""
    tf_publish_rate: 0.0
    diagnostics_period: 0.0
    decimation_filter.enable: false
    rosbag_filename: ""
    depth_module.exposure.1: 7500
    depth_module.gain.1: 16
    depth_module.exposure.2: 1
    depth_module.gain.2: 16
    wait_for_device_timeout: -1.
    reconnect_timeout: 6.