DriveControllerNode:
  ros_parameters:
    manualControlAllowed: true
    maxVelocity: 16093.0
    minVelocity: -16093.0
    driveGearRatio: 0.1
    wheelCircumference: 63.837
    maxSteeringVelocity: 0.0
    minSteeringVelocity: 0.0