DriveControllerNode:
  ros_parameters:
    manualControlAllowed: true
    maxVelocity: 16093.0
    minVelocity: 0.0
    driveGearRatio: 0.1
    wheelCircumference: 57.026
    steeringGearRatio: 0.667
    maxSteeringAngle: 45.0
    minSteeringAngle: -45.0